### PR TITLE
Add support for headers in notifications.

### PR DESCRIPTION
**Pull request by laurilehmijoki**
Also generate sources upon `mvn package`.

### CODE REVIEW

**Comment by drallgood** [comment]
Hey @laurilehmijoki 
Great work.

Do you think you could also update the change log file so that people know what you've changed?

**Comment by laurilehmijoki** [comment]
Hi @drallgood and thanks for the feedback. I've just updated the [CHANGELOG.md](https://github.com/laurilehmijoki/zencoder-java/commit/470641becb2a1ea1cb2bf0eb8fd130afc27d978d) in this pull request.

**Comment by drallgood** [comment]
Awesome. Thanks for your contribution!

**Comment by laurilehmijoki** [comment]
No prob, thanks for working on this helpful tool!

**Pull request merged**
